### ISSUE TITLE
[TASK-11.5C] Fix - Call to a member function set() on null after click on "Index Queue" -> "index now"

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#3088]
**What should be done in the scope of this task?**
That error must be fixed.
See attached Stack  trace in zip->html:
[Exception_trace_3088.zip](https://github.com/TYPO3-Solr/ext-solr/files/7442085/Exception_trace_3088.zip)

**Comment by dkd-kaehm** [comment]
### Fixed in https://github.com/TYPO3-Solr/ext-solr/commit/1307974e93960801037d038c6642ba59a8ded270

**Comment by bugskarl** [comment]
error still occures when trying to index pages which require FE session data -> f.ex. pages with a form+honeypot field.

may be solved by adding "$feUser->start($request);" in Classes/Middleware/FrontendUserAuthenticator->tryToAuthenticateFrontendUser() to initialize FE user session.

```
    protected function tryToAuthenticateFrontendUser(PageIndexerRequestHandler $handler, ServerRequestInterface $request): ServerRequestInterface
    {
        $accessRootline = $this->getAccessRootline($handler);
        $stringAccessRootline = (string)$accessRootline;

        if (empty($stringAccessRootline)) {
            return $request;
        }

        $groups = $accessRootline->getGroups();

        /* @var FrontendUserAuthentication $feUser */
        $feUser = GeneralUtility::makeInstance(FrontendUserAuthentication::class);
        $feUser->user[$feUser->username_column] = AuthorizationService::SOLR_INDEXER_USERNAME;
        /* @noinspection PhpParamsInspection */
        $this->context->setAspect('frontend.user', GeneralUtility::makeInstance(UserAspect::class, $feUser, $groups));
        $request = $request->withAttribute('frontend.user', $feUser);
        $feUser->start($request); // ADD

        return $request;
    }
```

**Comment by dkd-kaehm** [comment]
@bugskarl 
That is other context. The error in this issue about BE-Module "Index Queue".
Your issue is on indexing.
What exactly happens? And why do you want to index the page with forms, which is user int?
IMHO that was never possible.
Please try to add some Text content element to the page, the indexing for that page should work then. And the contents of usual content elements only will be indexed.

**Comment by MarkusEhrlich** [comment]
This fix does not seem to have arrived in the source code. The line

```$feUser->start($request);```

cannot be found in the code (/typo3conf/ext/solr/Classes/Middleware/FrontendUserAuthenticator.php).

**Comment by dkd-kaehm** [comment]
> This fix does not seem to have arrived in the source code. The line
> 
> `$feUser->start($request);`
> 
> cannot be found in the code (/typo3conf/ext/solr/Classes/Middleware/FrontendUserAuthenticator.php).

@MarkusEhrlich thanks for the hint. Re applied patch in release-11.5.x directly in #3163
