### ISSUE TITLE
Unset PageRenderer->backPath

### ISSUE THREAD

**Issue by cihanin2code** [TYPO3-Solr/ext-solr#646]
Usecase:
I'm doing an autoindexing inside my Hook by using existing functions of the solr-extension. The problem is that Util->initializeTsfe() initializes PageRenderer with "backpath" set to "typo3/". As soon as my Hook is finished I get this exception:
https://forge.typo3.org/issues/69319
Which in the end leads to non-responding TCE-Form.

So as we're in Backend Url's like 'typo3/typo3/.../FormEngine.js' are created and the JS-Files are not found. It would be great if we could say "$GLOBALS['TSFE']->getPageRenderer()->setBackPath('');" inside Util->initializeTsfe();

**Comment by irnnr** [comment]
What are you trying to do?

**Comment by cihanin2code** [comment]
Hey! :). 

This is my usecase: 
1) I've extra-authorization columns in sys_file_metadata
2) I'm indexing sys_file_metadata-records
3) I've implemented my own dynamic Filter which only fetches solr-indexes which match the currently logged in frontend user's authorization
4) As soon as a Backend-User changes an authorization-column in TCE-Form I want to automatically synchronize that data to the solr-index, because it's critical and I don't want the frontend-user to see stuff he is not authorized to.
--> Therefore: Inside my processDatamapClass-Hook I'm doing an autoupdate of the solr-Index. 
For this I've just copied the code of the "Indexer" into my own Service.
--> The problem with that is, that Indexer does initTSFE which sets PageRenderer->backPath to "typo3". 
--> But as I'm in Backend-context that is bad because TYPO3 starts rendering Javascript paths like this: "typo3/typo3/../FormEngine.js". 
--> As a result FormEngine.js is not found and after the operation of my Hook-Processor is finished the TCE-Form doesn't react anymore.

**Comment by timohund** [comment]
Since Util::initializeTSFE is used in many places, we need to test carefully before if this has any side effect on:

* Indexing of pages and records (especially urls in backend and cli context)
* Retrieval of configuration

When we know, all of this still works as expected i think we could changes this.

**Comment by timohund** [comment]
Since no additional feedback was provided, i'll close this issue. Please open a new one when you still have any issues with that.
